/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author ASUS
 */
public class userHome extends javax.swing.JFrame {

    /**
     * Creates new form userHome
     */
    public userHome() {
        initComponents();
        bluePanel.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        panel1 = new java.awt.Panel();
        profile = new javax.swing.JLabel();
        borrowsButton = new javax.swing.JButton();
        reservationButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        historyButton = new javax.swing.JButton();
        notificationsButton = new javax.swing.JButton();
        booksButton = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        grayPanel = new java.awt.Panel();
        bookSearch = new javax.swing.JTextField();
        panel4 = new java.awt.Panel();
        bluePanel = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        mathPhoto = new javax.swing.JLabel();
        englishPhoto = new javax.swing.JLabel();
        sciencePhoto = new javax.swing.JLabel();
        scienceButton = new javax.swing.JButton();
        mathButton = new javax.swing.JButton();
        searchIcon = new javax.swing.JLabel();
        englishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(26, 27, 27));
        panel2.setPreferredSize(new java.awt.Dimension(1400, 20));
        panel2.setLayout(new javax.swing.OverlayLayout(panel2));
        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1140, 20));

        panel1.setBackground(new java.awt.Color(26, 27, 27));
        panel1.setPreferredSize(new java.awt.Dimension(100, 1000));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\JavaPractice\\UserInterface\\icons\\whiteIcon.png")); // NOI18N
        panel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        borrowsButton.setBackground(new java.awt.Color(26, 27, 27));
        borrowsButton.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        borrowsButton.setForeground(java.awt.Color.white);
        borrowsButton.setText("Borrows");
        borrowsButton.setActionCommand("");
        borrowsButton.setBorder(null);
        borrowsButton.setBorderPainted(false);
        borrowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowsButtonActionPerformed(evt);
            }
        });
        panel1.add(borrowsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, -1));

        reservationButton.setBackground(new java.awt.Color(26, 27, 27));
        reservationButton.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        reservationButton.setForeground(java.awt.Color.white);
        reservationButton.setText("Reservation");
        reservationButton.setBorder(null);
        reservationButton.setBorderPainted(false);
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });
        panel1.add(reservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        settingsButton.setBackground(new java.awt.Color(26, 27, 27));
        settingsButton.setFont(new java.awt.Font("Swis721 Lt BT", 1, 18)); // NOI18N
        settingsButton.setForeground(java.awt.Color.white);
        settingsButton.setText("Settings");
        settingsButton.setBorder(null);
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        panel1.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jSeparator1.setBackground(java.awt.Color.white);
        jSeparator1.setPreferredSize(new java.awt.Dimension(70, 10));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, -1));

        historyButton.setBackground(new java.awt.Color(26, 27, 27));
        historyButton.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        historyButton.setForeground(java.awt.Color.white);
        historyButton.setText("History");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        panel1.add(historyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        notificationsButton.setBackground(new java.awt.Color(26, 27, 27));
        notificationsButton.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        notificationsButton.setForeground(java.awt.Color.white);
        notificationsButton.setText("Notifications");
        notificationsButton.setBorder(null);
        notificationsButton.setBorderPainted(false);
        panel1.add(notificationsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        booksButton.setBackground(new java.awt.Color(26, 27, 27));
        booksButton.setFont(new java.awt.Font("Stylus BT", 1, 18)); // NOI18N
        booksButton.setForeground(java.awt.Color.white);
        booksButton.setText("Books");
        booksButton.setActionCommand("Borrowing");
        booksButton.setBorder(null);
        booksButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        booksButton.setFocusPainted(false);
        booksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksButtonActionPerformed(evt);
            }
        });
        panel1.add(booksButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        userName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userName.setForeground(java.awt.Color.white);
        userName.setText("User Name");
        panel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 790));

        grayPanel.setBackground(new java.awt.Color(118, 118, 126));
        grayPanel.setMaximumSize(null);
        grayPanel.setName(""); // NOI18N
        grayPanel.setPreferredSize(new java.awt.Dimension(910, 740));

        bookSearch.setBackground(new java.awt.Color(26, 27, 27));
        bookSearch.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        bookSearch.setForeground(java.awt.Color.white);
        bookSearch.setText("Search here");
        bookSearch.setAlignmentX(0.0F);
        bookSearch.setAlignmentY(0.0F);
        bookSearch.setMaximumSize(null);
        bookSearch.setMinimumSize(null);
        bookSearch.setPreferredSize(new java.awt.Dimension(690, 28));

        panel4.setBackground(new java.awt.Color(204, 204, 204));
        panel4.setPreferredSize(new java.awt.Dimension(780, 554));
        panel4.setLayout(null);

        bluePanel.setBackground(new java.awt.Color(48, 72, 96));

        booksTable.setBackground(new java.awt.Color(26, 27, 27));
        booksTable.setFont(new java.awt.Font("STSong", 1, 14)); // NOI18N
        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Book Title", "Book #", "Date of Borrow", "Date of Return"
            }
        ));
        jScrollPane1.setViewportView(booksTable);

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        panel4.add(bluePanel);
        bluePanel.setBounds(0, 0, 730, 610);

        mathPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\JavaPractice\\UserInterface\\icons\\mathPhoto.jpg")); // NOI18N
        panel4.add(mathPhoto);
        mathPhoto.setBounds(500, 120, 200, 330);
        sciencePhoto.setVisible(false);

        mathPhoto.setVisible(false);

        englishPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\JavaPractice\\UserInterface\\icons\\english.jpg")); // NOI18N
        panel4.add(englishPhoto);
        englishPhoto.setBounds(390, 100, 200, 300);
        englishPhoto.setVisible(false);

        sciencePhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\JavaPractice\\UserInterface\\icons\\science.jpg")); // NOI18N
        sciencePhoto.setText(" ");
        panel4.add(sciencePhoto);
        sciencePhoto.setBounds(510, 290, 207, 300);
        sciencePhoto.setVisible(false);

        scienceButton.setBackground(new java.awt.Color(255, 255, 255));
        scienceButton.setForeground(new java.awt.Color(26, 27, 27));
        scienceButton.setText("Science");
        scienceButton.setBorder(null);
        scienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceButtonActionPerformed(evt);
            }
        });

        mathButton.setBackground(new java.awt.Color(255, 255, 255));
        mathButton.setForeground(new java.awt.Color(26, 27, 27));
        mathButton.setText("Mathematics");
        mathButton.setBorder(null);
        mathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathButtonActionPerformed(evt);
            }
        });

        searchIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\JavaPractice\\UserInterface\\icons\\search.png")); // NOI18N

        englishButton.setBackground(new java.awt.Color(255, 255, 255));
        englishButton.setForeground(new java.awt.Color(26, 27, 27));
        englishButton.setText("English");
        englishButton.setBorder(null);
        englishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grayPanelLayout = new javax.swing.GroupLayout(grayPanel);
        grayPanel.setLayout(grayPanelLayout);
        grayPanelLayout.setHorizontalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPanelLayout.createSequentialGroup()
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
            .addGroup(grayPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grayPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mathButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grayPanelLayout.setVerticalGroup(
            grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPanelLayout.createSequentialGroup()
                .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(grayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(grayPanelLayout.createSequentialGroup()
                                .addComponent(englishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scienceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(grayPanelLayout.createSequentialGroup()
                        .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        getContentPane().add(grayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 910, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowsButtonActionPerformed
                   bluePanel.setVisible(true);                   
    }//GEN-LAST:event_borrowsButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyButtonActionPerformed

    private void booksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksButtonActionPerformed
       
    }//GEN-LAST:event_booksButtonActionPerformed

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
                    
        Reservation rsv = new Reservation ();
         grayPanel.add(rsv.reservation);
       
         
         
        
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void scienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceButtonActionPerformed
         
         
    }//GEN-LAST:event_scienceButtonActionPerformed

    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishButtonActionPerformed
        
    }//GEN-LAST:event_englishButtonActionPerformed

    private void mathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathButtonActionPerformed

    }//GEN-LAST:event_mathButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel bluePanel;
    private javax.swing.JTextField bookSearch;
    private javax.swing.JButton booksButton;
    private javax.swing.JTable booksTable;
    private javax.swing.JButton borrowsButton;
    private javax.swing.JButton englishButton;
    private javax.swing.JLabel englishPhoto;
    private java.awt.Panel grayPanel;
    private javax.swing.JButton historyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mathButton;
    private javax.swing.JLabel mathPhoto;
    private javax.swing.JButton notificationsButton;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private javax.swing.JLabel profile;
    private javax.swing.JButton reservationButton;
    private javax.swing.JButton scienceButton;
    private javax.swing.JLabel sciencePhoto;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
